<?php
/**
 * REST helpers: AI-generated post guard (same meta as AAPG_AI_Post_Controller).
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Require post exists and was marked as generated by automation.
 *
 * @param int $post_id Post ID.
 * @return true|\WP_Error
 */
function aapg_rest_require_ai_generated_post(int $post_id) {
    $post = get_post($post_id);
    if (!$post) {
        return new \WP_Error('rest_post_invalid', __('Post not found.', 'aapg'), ['status' => 404]);
    }
    if (get_post_meta($post_id, 'isGeneratedByAutomation', true) !== 'true') {
        return new \WP_Error(
            'rest_not_ai_generated',
            __('This post was not generated by automation. This API only applies to AI-generated content.', 'aapg'),
            ['status' => 403]
        );
    }
    return true;
}
