<?php
/**
 * AAPG REST API: AI-generated post verification and status (draft/publish).
 * Single endpoint: verify by post ID, move to draft, or convert to publish.
 */

namespace AAPG\Rest;

if (!defined('ABSPATH')) {
    exit;
}

class AAPG_AI_Post_Controller extends \WP_REST_Controller {

    const REST_NAMESPACE = 'aapg/v1';
    const REST_ROUTE = 'ai-post';

    /** Meta key used to mark AI-generated content. */
    const META_AI_GENERATED = 'isGeneratedByAutomation';

    public function register_routes(): void {
        register_rest_route(self::REST_NAMESPACE, '/' . self::REST_ROUTE, [
            [
                'methods'             => \WP_REST_Server::READABLE,
                'callback'            => [$this, 'get_item'],
                'permission_callback' => [$this, 'check_api_key'],
                'args'                => $this->get_get_params(),
            ],
            [
                'methods'             => \WP_REST_Server::CREATABLE,
                'callback'            => [$this, 'update_status'],
                'permission_callback' => [$this, 'check_api_key'],
                'args'                => $this->get_post_params(),
            ],
        ]);
    }

    /**
     * Permission callback: validate API key from header or query.
     */
    public function check_api_key(\WP_REST_Request $request): bool|\WP_Error {
        $settings = get_option(AAPG_OPTION_KEY, []);
        $stored_key = $settings['aapg_rest_api_key'] ?? '';
        if (empty($stored_key)) {
            return new \WP_Error('rest_disabled', __('REST API is disabled. Set an API key in settings.', 'aapg'), ['status' => 401]);
        }
        $header_key = $request->get_header('X-AAPG-API-Key');
        $query_key = $request->get_param('api_key');
        $provided = $header_key ?: $query_key;
        if (!is_string($provided) || $provided === '' || !hash_equals($stored_key, $provided)) {
            return new \WP_Error('rest_forbidden', __('Invalid or missing API key.', 'aapg'), ['status' => 401]);
        }
        return true;
    }

    public function get_get_params(): array {
        return [
            'post_id' => [
                'required'          => true,
                'type'              => 'integer',
                'minimum'           => 1,
                'description'       => __('Post or page ID to verify.', 'aapg'),
                'sanitize_callback' => 'absint',
            ],
        ];
    }

    public function get_post_params(): array {
        return [
            'post_id' => [
                'required'          => true,
                'type'              => 'integer',
                'minimum'           => 1,
                'description'       => __('Post or page ID.', 'aapg'),
                'sanitize_callback' => 'absint',
            ],
            'action' => [
                'required'          => true,
                'type'              => 'string',
                'enum'              => ['to_draft', 'to_publish'],
                'description'       => __('Action: to_draft (move to draft) or to_publish (convert to publish).', 'aapg'),
            ],
        ];
    }

    /**
     * GET: Verify if the post is AI-generated and return current status.
     *
     * @param \WP_REST_Request $request Request object.
     * @return \WP_REST_Response|\WP_Error
     */
    public function get_item($request) {
        $post_id = $request->get_param('post_id');
        $post = get_post($post_id);

        if (!$post) {
            return new \WP_Error('rest_post_invalid', __('Post not found.', 'aapg'), ['status' => 404]);
        }

        $is_ai_generated = get_post_meta($post_id, self::META_AI_GENERATED, true) === 'true';

        return new \WP_REST_Response([
            'post_id'         => (int) $post_id,
            'is_ai_generated' => $is_ai_generated,
            'post_type'       => $post->post_type,
            'post_status'     => $post->post_status,
            'post_title'      => $post->post_title,
        ], 200);
    }

    /**
     * POST: Verify AI-generated and then move to draft or publish.
     */
    public function update_status(\WP_REST_Request $request): \WP_REST_Response|\WP_Error {
        $post_id = $request->get_param('post_id');
        $action = $request->get_param('action');

        $post = get_post($post_id);
        if (!$post) {
            return new \WP_Error('rest_post_invalid', __('Post not found.', 'aapg'), ['status' => 404]);
        }

        $is_ai_generated = get_post_meta($post_id, self::META_AI_GENERATED, true) === 'true';
        if (!$is_ai_generated) {
            return new \WP_Error(
                'rest_not_ai_generated',
                __('This post/page was not generated by automation. Only AI-generated content can be moved to draft or published via this API.', 'aapg'),
                ['status' => 400]
            );
        }

        $new_status = $action === 'to_draft' ? 'draft' : 'publish';
        $previous_status = $post->post_status;

        if ($previous_status === $new_status) {
            return new \WP_REST_Response([
                'success'         => true,
                'post_id'         => (int) $post_id,
                'is_ai_generated'  => true,
                'previous_status' => $previous_status,
                'current_status'  => $new_status,
                'message'         => sprintf(
                    /* translators: %s: post status */
                    __('Post is already %s.', 'aapg'),
                    $new_status
                ),
            ], 200);
        }

        $result = wp_update_post([
            'ID'          => $post_id,
            'post_status' => $new_status,
        ], true);

        if (is_wp_error($result)) {
            return new \WP_Error(
                'rest_update_failed',
                __('Failed to update post status: ', 'aapg') . $result->get_error_message(),
                ['status' => 500]
            );
        }

        $post_type_obj = get_post_type_object($post->post_type);
        $label = $post_type_obj ? $post_type_obj->labels->singular_name : $post->post_type;
        $message = $new_status === 'publish'
            ? sprintf(__('%s published successfully.', 'aapg'), $label)
            : sprintf(__('%s moved to draft.', 'aapg'), $label);

        return new \WP_REST_Response([
            'success'         => true,
            'post_id'         => (int) $post_id,
            'is_ai_generated' => true,
            'previous_status' => $previous_status,
            'current_status'  => $new_status,
            'message'         => $message,
            'permalink'       => aapg_id_based_post_url($post_id),
            'edit_link'       => get_edit_post_link($post_id, 'raw'),
        ], 200);
    }
}
